language: php

php:
  - '7.0'
  - '7.1'
  - hhvm

# optionally set up exclutions and allowed failures in the matrix
matrix:
  allow_failures:
    - php: 7.1
    - php: hhvm

before_install:
 - chmod +x ./tests/install_dependencies.sh

install:
  - ./tests/install_dependencies.sh

script: phpunit --configuration tests/phpunit.xml --coverage-text
